/* Autogenerated by png2wx.pl on Sun Jun 16 00:58:12 2024 */
#ifndef TWOCANAUTOPILOT_IMAGES_H
#define TWOCANAUTOPILOT_IMAGES_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_compass;
extern wxBitmap *_img_power;
extern wxBitmap *_img_wind;
extern wxBitmap *_img_track;
extern wxBitmap *_img_autopilot;
extern wxBitmap *_img_right_one;
extern wxBitmap *_img_right_ten;
extern wxBitmap *_img_left_one;
extern wxBitmap *_img_left_ten;

#endif /* TWOCANAUTOPILOT_IMAGES_H */
