/* Autogenerated by png2wx.pl on Thu Nov 11 18:29:10 2021 */
#ifndef AUTOPILOT_ICON_H
#define AUTOPILOT_ICON_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *autopilotLogo;

#endif /* AUTOPILOT_ICON_H */
