/* Autogenerated by png2wx.pl on Wed Apr  6 23:35:44 2022 */
#ifndef F_HPP
#define F_HPP 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *pluginIcon;

#endif /* F_HPP */
